
server :
  port : 8761
  spring:
    application:
      name: busvia-service-registry
      cloud:
        config:
          uri: http://localhost:8761
eureka :
  client :
    register-with-eureka : false
    fetch-registry : false


#server:
#  port: 8761

#eureka:
#  instance:
#    hostname: 154.169.219.205
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://54.169.219.205:8761/eureka/
#server:
#  port: 8761
#
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false


